name: dc

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
  ui:
    image: node:21
    volumes:
      - type: bind
        target: /src/app
        source: ./ui
    working_dir: /src/app
    command: 
      - npm
      - run
      - dev
    ports:
      - 8001:8001
  cache:
    image: redis:7.2.4
