name: dc

services:
  api:
    image: golang:1.22
    volumes:
      - type: bind
        target: /go/src/app
        source: ./api
    working_dir: /go/src/app
    command: 
      - go
      - run
      - main.go
    ports:
      - 8001:8090
  fe:
    image: node:21
    volumes:
      - type: bind
        target: /src/app
        source: ./fe
    working_dir: /src/app
    command: 
      - npm
      - run
      - dev
    ports:
      - 8000:8000
  cache:
    image: redis:7.2.4
